name: Publish Hot Fix

on:
  workflow_dispatch:

concurrency:
  group: $${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false
  queue: max

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: npm

      # Ensure tests pass. Add more checks if required
      - run: npm ci --ignore-scripts
      - run: npm test

      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@f95d7ca6ee42255191e17bbf5dd8e08810a189a3 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
