name: Validate Template

on:
  pull_request:
    branches:
      - main
      - minimal
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Validate Template Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Check container starts in production-like mode
        run: .github/template/validate.sh
